name: generate 3D contribution graph

on:
  schedule:
    - cron: "0 18 * * 1,4"
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/profile-3d.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate 3d contribution graph
    steps:
      - uses: actions/checkout@v5

      - uses: yoshi389111/github-profile-3d-contrib@v0.9.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "chore: update 3D contribution graph"; then
            git push
          fi
